# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_crypto_fields.fields.encrypted_text_field
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edc_registration', '0002_auto_20160503_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('subject', models.CharField(max_length=50, unique=True, verbose_name='Subject line')),
                ('action_date', models.DateField(default=datetime.date(2016, 5, 4), verbose_name='action_date')),
                ('expiration_date', models.DateField(default=datetime.date(2016, 8, 2), help_text="Data note will automatically be set to 'Resolved' in 90 days unless otherwise specified.")),
                ('comment', django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(help_text=' (Encryption: AES local) (Encryption: AES local)')),
                ('display_on_dashboard', models.BooleanField(default=True)),
                ('rt', models.IntegerField(default=0, verbose_name='RT Ref.')),
                ('action_priority', models.CharField(choices=[('normal', 'Normal'), ('Medium', 'Medium'), ('high', 'High')], default='Normal', max_length=35)),
                ('action_group', models.CharField(default='no group', help_text='You can only select a group to which you belong. Choices are based on Groups defined in Auth.', max_length=35)),
                ('status', models.CharField(choices=[('open', 'Open'), ('stalled', 'Stalled'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text="Only data managers or study physicians can 'close' an action item", max_length=35)),
                ('registered_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_registration.RegisteredSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('subject', models.CharField(max_length=50)),
                ('comment_date', models.DateField(default=datetime.date(2016, 5, 4))),
                ('comment', django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(help_text=' (Encryption: AES local) (Encryption: AES local)')),
                ('rt', models.IntegerField(default=0, verbose_name='RT Ref.')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Stalled', 'Stalled'), ('Resolved', 'Resolved')], default='Open', max_length=35)),
            ],
        ),
    ]
