# Generated by Django 3.0.5 on 2020-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0002_dataactionitem_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataactionitem',
            name='assign',
            field=models.CharField(max_length=50, verbose_name='Assign to'),
        ),
    ]
