# Generated by Django 3.0.5 on 2020-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0004_auto_20200423_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataactionitem',
            name='assign',
            field=models.CharField(blank=True, choices=[(None, 'None')], max_length=50, null=True, verbose_name='Assign to'),
        ),
    ]
