# Generated by Django 3.0.5 on 2020-04-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0005_auto_20200423_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataactionitem',
            old_name='assign',
            new_name='assigned',
        ),
    ]
