# Generated by Django 3.0.5 on 2020-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0006_auto_20200423_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataactionitem',
            name='assigned',
            field=models.CharField(default='', max_length=50, verbose_name='Assign to'),
            preserve_default=False,
        ),
    ]
