# Generated by Django 4.1 on 2023-10-09 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0007_auto_20200423_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataactionitem',
            name='subject_type',
            field=models.CharField(choices=[('infant', 'Infant'), ('maternal', 'Maternal'), ('subject', 'Subject')], default='subject', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataactionitem',
            name='action_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Action date'),
        ),
    ]
