# Generated by Django 3.1.14 on 2022-03-17 01:00

import _socket
import datetime
from django.db import migrations, models
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0007_auto_20200423_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryName',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('query_name', models.CharField(max_length=200, unique=True, verbose_name='Name of the Query')),
            ],
        ),
        migrations.AddField(
            model_name='dataactionitem',
            name='query_name',
            field=models.CharField(default='Not Categorized', max_length=200, verbose_name='Name of the Query'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataactionitem',
            name='subject_type',
            field=models.CharField(choices=[('infant', 'Infant'), ('maternal', 'Maternal'), ('subject', 'Subject')], default='subject', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataactionitem',
            name='action_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Action date'),
        ),
    ]
