# Generated by Django 3.1.14 on 2022-03-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0008_auto_20220317_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataactionitem',
            name='new_query_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='New Query Name'),
        ),
    ]
