# Generated by Django 3.1.14 on 2022-03-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0009_dataactionitem_new_query_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataactionitem',
            unique_together={('subject_identifier', 'query_name')},
        ),
    ]
